# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Netresearch DTT GmbH

extends: default

ignore:
  - "skills/*/assets/"

rules:
  line-length: {max: 120, level: warning}
  comments-indentation: disable
